import type { Locale } from '../config/site';

export const serviceDetailCopy = {
  id: {
    seo: {
      titlePrefix: 'Jasa',
      titleSuffix: 'Resmi & Terpercaya | Awan Kusuma Legalitas',
      descriptionPrefix: 'Jasa',
      descriptionBody: 'resmi, cepat & terpercaya bersama Awan Kusuma.',
      pricePrefix: 'Harga mulai',
      descriptionSuffix: 'Proses transparan dan konsultasi gratis.',
      schemaFallback: 'Layanan profesional dari Awan Kusuma Legalitas.',
      home: 'Beranda',
      services: 'Layanan',
    },
    back: 'Kembali',
    hero: {
      prefix: 'Jasa',
      suffix: 'lebih Mudah bersama Kami',
      fallbackName: 'Layanan Kami',
      fallbackDescription: 'Layanan komprehensif dengan proses yang transparan, aman, dan efisien untuk mendukung legalitas bisnis Anda.',
      consultation: 'Konsultasi Gratis',
      pricing: 'Lihat Harga',
      whatsappTemplate: 'Halo Awan Kusuma Legalitas! 👋 Saya tertarik dengan layanan {service}. Bisa konsultasi gratis?',
      fallbackService: 'legalitas bisnis',
    },
    about: {
      kicker: 'Fundamental Layanan',
      titleTemplate: 'Apa itu {service}?',
    },
    process: {
      kicker: 'Alur Kerja',
      titleHtml: 'Semudah <br /><span class="text-white">4 Langkah</span>',
      description: 'Proses yang sederhana, transparan, dan tanpa ribet. Kami yang mengurus kompleksitas birokrasi, Anda yang fokus mengembangkan bisnis.',
      clients: 'Klien Terlayani',
      processingTime: 'Hari Kerja Proses',
      officialNotary: 'Notaris Resmi',
      free: 'Gratis',
      initialConsultation: 'Konsultasi Awal',
      steps: [
        { title: 'Konsultasi Gratis', description: 'Diskusikan kebutuhan bisnis Anda dengan tim ahli kami.' },
        { title: 'Lengkapi Dokumen', description: 'Serahkan dokumen yang dibutuhkan secara online.' },
        { title: 'Proses Pengurusan', description: 'Tim legal kami akan mengurus semua proses ke instansi.' },
        { title: 'Dokumen Selesai', description: 'Dokumen resmi siap dan langsung dikirim ke Anda.' },
      ],
    },
    pricing: {
      unavailable: 'Informasi harga untuk layanan ini sedang disiapkan.',
      title: 'Pilih Paket Kebutuhan',
      description: 'Transparan, tanpa biaya tersembunyi. Mulailah perjalanan bisnis Anda dengan fondasi legalitas yang kokoh bersama tim Awan Kusuma.',
      priceFeatures: 'Harga & Fitur',
      requirements: 'Syarat Dokumen',
      popular: 'Paling Populer',
      generalRequirements: 'Persyaratan Umum',
      requirementsFallback: 'Hubungi kami untuk detail persyaratan.',
      orderNow: 'Pesan Sekarang',
      whatsappTemplate: 'Halo Awan Kusuma Legalitas! 👋 Saya tertarik dengan paket *{package}*{servicePart}. Bisa konsultasi lebih lanjut?',
      whatsappServiceTemplate: ' untuk layanan *{service}*',
    },
    addons: {
      title: 'Paket Layanan Tambahan',
      description: 'Perizinan usaha dan pengurusan pajak dalam satu layanan. Temukan kemudahan pengurusannya bersama Awan Kusuma Legalitas.',
    },
    testimonials: {
      kicker: 'Suara Klien',
      title: 'Bukti Nyata',
      titleAccent: 'Kepercayaan',
      descriptionTemplate: 'Pengalaman langsung klien yang telah menggunakan layanan {service}.',
      previous: 'Testimonial sebelumnya',
      next: 'Testimonial berikutnya',
    },
    faq: {
      kicker: 'Mulai Konsultasi',
      contact: 'Hubungi Kami',
      serviceQuestionTemplate: 'Punya pertanyaan lebih spesifik mengenai layanan {service}?',
      generalPrompt: 'Ceritakan kebutuhan bisnis Anda kepada kami.',
      fullName: 'Nama Lengkap',
      whatsappNumber: 'Nomor WhatsApp',
      message: 'Pesan / Pertanyaan',
      send: 'Kirim Pesan',
      titleLine1: 'Pertanyaan',
      titleLine2: 'Umum',
      descriptionTemplate: 'Temukan jawaban cepat untuk keraguan Anda seputar {service}.',
      fallbackService: 'layanan kami',
      whatsappGreeting: 'Halo Awan Kusuma Legalitas! 👋',
      whatsappIntro: 'Saya {name} ingin berkonsultasi{servicePart}.',
      whatsappServiceTemplate: ' mengenai layanan {service}',
      whatsappPhone: 'Nomor HP',
      whatsappMessage: 'Pesan',
    },
  },
  en: {
    seo: {
      titlePrefix: 'Professional',
      titleSuffix: 'Service | Awan Kusuma Legalitas',
      descriptionPrefix: 'Professional',
      descriptionBody: 'service delivered reliably and efficiently by Awan Kusuma.',
      pricePrefix: 'Starting from',
      descriptionSuffix: 'Transparent process and free consultation.',
      schemaFallback: 'Professional service from Awan Kusuma Legalitas.',
      home: 'Home',
      services: 'Services',
    },
    back: 'Back',
    hero: {
      prefix: 'Professional',
      suffix: 'made Easier with Us',
      fallbackName: 'Business Service',
      fallbackDescription: 'A comprehensive service with a transparent, secure, and efficient process to support your business compliance.',
      consultation: 'Free Consultation',
      pricing: 'View Pricing',
      whatsappTemplate: 'Hello Awan Kusuma Legalitas! 👋 I am interested in the {service} service. May I get a free consultation?',
      fallbackService: 'business compliance',
    },
    about: {
      kicker: 'Service Fundamentals',
      titleTemplate: 'What is {service}?',
    },
    process: {
      kicker: 'How It Works',
      titleHtml: 'Simple in <br /><span class="text-white">4 Steps</span>',
      description: 'A simple, transparent, and hassle-free process. We handle the administrative complexity so you can focus on growing your business.',
      clients: 'Clients Served',
      processingTime: 'Business Days',
      officialNotary: 'Licensed Notary',
      free: 'Free',
      initialConsultation: 'Initial Consultation',
      steps: [
        { title: 'Free Consultation', description: 'Discuss your business needs with our expert team.' },
        { title: 'Submit Documents', description: 'Send the required documents securely online.' },
        { title: 'Application Process', description: 'Our legal team handles the process with the relevant authorities.' },
        { title: 'Documents Completed', description: 'Your official documents are completed and delivered to you.' },
      ],
    },
    pricing: {
      unavailable: 'Pricing information for this service is being prepared.',
      title: 'Choose Your Package',
      description: 'Transparent pricing with no hidden fees. Build a strong legal foundation for your business with Awan Kusuma.',
      priceFeatures: 'Price & Features',
      requirements: 'Required Documents',
      popular: 'Most Popular',
      generalRequirements: 'General Requirements',
      requirementsFallback: 'Contact us for detailed requirements.',
      orderNow: 'Get Started',
      whatsappTemplate: 'Hello Awan Kusuma Legalitas! 👋 I am interested in the *{package}* package{servicePart}. May I get more information?',
      whatsappServiceTemplate: ' for the *{service}* service',
    },
    addons: {
      title: 'Additional Service Packages',
      description: 'Business licensing and tax administration in one service. Manage everything more easily with Awan Kusuma Legalitas.',
    },
    testimonials: {
      kicker: 'Client Stories',
      title: 'Real Proof of',
      titleAccent: 'Trust',
      descriptionTemplate: 'First-hand experiences from clients who have used our {service} service.',
      previous: 'Previous testimonial',
      next: 'Next testimonial',
    },
    faq: {
      kicker: 'Start a Consultation',
      contact: 'Contact Us',
      serviceQuestionTemplate: 'Have a specific question about our {service} service?',
      generalPrompt: 'Tell us what your business needs.',
      fullName: 'Full Name',
      whatsappNumber: 'WhatsApp Number',
      message: 'Message / Question',
      send: 'Send Message',
      titleLine1: 'Frequently Asked',
      titleLine2: 'Questions',
      descriptionTemplate: 'Find quick answers to common questions about {service}.',
      fallbackService: 'our services',
      whatsappGreeting: 'Hello Awan Kusuma Legalitas! 👋',
      whatsappIntro: 'My name is {name}, and I would like a consultation{servicePart}.',
      whatsappServiceTemplate: ' about the {service} service',
      whatsappPhone: 'Phone Number',
      whatsappMessage: 'Message',
    },
  },
  zh: {
    seo: {
      titlePrefix: '专业',
      titleSuffix: '服务 | Awan Kusuma Legalitas',
      descriptionPrefix: '专业',
      descriptionBody: '服务，由 Awan Kusuma 提供可靠、高效的办理支持。',
      pricePrefix: '价格从',
      descriptionSuffix: '流程透明，并提供免费咨询。',
      schemaFallback: 'Awan Kusuma Legalitas 提供的专业服务。',
      home: '首页',
      services: '服务',
    },
    back: '返回',
    hero: {
      prefix: '专业',
      suffix: '由我们为您轻松办理',
      fallbackName: '企业服务',
      fallbackDescription: '通过透明、安全、高效的流程，为您的企业合规提供全面支持。',
      consultation: '免费咨询',
      pricing: '查看价格',
      whatsappTemplate: '您好，Awan Kusuma Legalitas！👋 我对{service}服务感兴趣，可以免费咨询吗？',
      fallbackService: '企业合规',
    },
    about: {
      kicker: '服务简介',
      titleTemplate: '什么是{service}？',
    },
    process: {
      kicker: '办理流程',
      titleHtml: '轻松完成 <br /><span class="text-white">4 个步骤</span>',
      description: '流程简单、透明、省心。繁琐的行政手续由我们处理，让您专注于业务发展。',
      clients: '已服务客户',
      processingTime: '工作日',
      officialNotary: '持牌公证人',
      free: '免费',
      initialConsultation: '初步咨询',
      steps: [
        { title: '免费咨询', description: '与我们的专业团队沟通您的企业需求。' },
        { title: '提交文件', description: '在线安全提交所需文件。' },
        { title: '办理申请', description: '我们的法律团队将与相关机构完成办理流程。' },
        { title: '文件完成', description: '正式文件完成后将直接交付给您。' },
      ],
    },
    pricing: {
      unavailable: '该服务的价格信息正在准备中。',
      title: '选择服务套餐',
      description: '价格透明，无隐藏费用。与 Awan Kusuma 一起为您的企业建立稳固的法律基础。',
      priceFeatures: '价格与内容',
      requirements: '所需文件',
      popular: '最受欢迎',
      generalRequirements: '一般要求',
      requirementsFallback: '请联系我们了解详细要求。',
      orderNow: '立即咨询',
      whatsappTemplate: '您好，Awan Kusuma Legalitas！👋 我对 *{package}* 套餐感兴趣{servicePart}，可以进一步咨询吗？',
      whatsappServiceTemplate: '，用于 *{service}* 服务',
    },
    addons: {
      title: '附加服务套餐',
      description: '企业许可与税务办理一站式服务。与 Awan Kusuma Legalitas 一起更轻松地完成相关手续。',
    },
    testimonials: {
      kicker: '客户评价',
      title: '真实见证',
      titleAccent: '值得信赖',
      descriptionTemplate: '了解客户使用{service}服务后的真实体验。',
      previous: '上一条客户评价',
      next: '下一条客户评价',
    },
    faq: {
      kicker: '开始咨询',
      contact: '联系我们',
      serviceQuestionTemplate: '对{service}服务有更具体的问题吗？',
      generalPrompt: '请告诉我们您的企业需求。',
      fullName: '姓名',
      whatsappNumber: 'WhatsApp 号码',
      message: '留言 / 问题',
      send: '发送消息',
      titleLine1: '常见',
      titleLine2: '问题',
      descriptionTemplate: '快速了解有关{service}的常见问题。',
      fallbackService: '我们的服务',
      whatsappGreeting: '您好，Awan Kusuma Legalitas！👋',
      whatsappIntro: '我是{name}，希望咨询{servicePart}。',
      whatsappServiceTemplate: '{service}服务',
      whatsappPhone: '电话号码',
      whatsappMessage: '留言',
    },
  },
} satisfies Record<Locale, Record<string, unknown>>;
